package $Expertise.DataStructures.implemented.Problems;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class PhoneNumberLetterCombination {
    /**
     * <h1> To find the number of possible combinantions that can be generated by Pressing numbers on a keypad phone</h1>
     * <h1>Approach</h1>
     * <li>Create the Key Map</li>
     * <li>base case - if combinations == len of keysPress then add the currCombination to ans and return</li>
     * <li>Start from iterating over KeyPress Numbers</li>
     * <li>and then the output characters of the respective KeyPress</li>
     * <li>Then call the function</li>
     * <li>At the end remove the last character from the StringBuilder</li>
     */

    public static  void keyWordBuilder(int i,StringBuilder currWord,int keyLength,List<String> finalAns,
                                       HashMap<String,String> keyMap, String keyPress){
        if (currWord.length()==keyLength) {
            finalAns.add(currWord.toString());
            return;
        }

        String letters = keyMap.get(String.valueOf(keyPress.charAt(i)));

            for (char ch : letters.toCharArray()) {
                currWord.append(ch);
                keyWordBuilder(i + 1, currWord, keyLength, finalAns, keyMap, keyPress);
                currWord.deleteCharAt(currWord.length() - 1); // backtrack
            }

    }
    public static void main(String[] args) {

        HashMap<String,String> keyMap= new HashMap<>();
        keyMap.put("2","abc");
        keyMap.put("3","def");
        keyMap.put("4","ghi");
        keyMap.put("5","jkl");
        keyMap.put("6","mno");
        keyMap.put("7","pqrs");
        keyMap.put("8","tuv");
        keyMap.put("9","wxyz");

        List<String> finalAns= new ArrayList<>();
        String keyPres="23";
        StringBuilder finalWord= new StringBuilder();

        if (keyPres.length()==0)
            System.out.println("");
        else
            keyWordBuilder(0,finalWord,keyPres.length(),finalAns,keyMap,keyPres);
        System.out.println(finalAns);

    }
}
